### ISSUE TITLE
Add fault tolerance mechanism

### ISSUE THREAD

**Issue by xiaoniuchushi** [qiuqiangkong/piano_transcription_inference#1]
Thank you for publishing the model.
In pypi's package, when the audio model can't turn notes, the program will report an error. Instead of outputting an empty midi. The wrong place is in line 397 of _piano_transcription_inference/utilities.py_.
And there are some audio models that can't be identified.

**Comment by qiuqiangkong** [comment]
Thanks for reporting the issue!
